backend:
  name: github
  repo: plemonsbrett/portfolio-project
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - label: "SEO Settings"
        name: "seo"
        file: "content/settings.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Meta Description", name: "description", widget: "text" }
          - { label: "Keywords", name: "keywords", widget: "list", default: [] }
  - name: "homepage"
    label: "Homepage Content"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/homepage.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "CTA Button Text", name: "ctaText", widget: "string" }
          - { label: "CTA Button Link", name: "ctaLink", widget: "string" }
    
